#!/bin/bash -ex

DB_NAME=drupal9
DB_USER=drupal9
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/drupal9

PHP_V=7.3
USER=www-data

# set proxy settings
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

# increase php cli memory limit - for composer install.
sed -i "s|^memory_limit.*|memory_limit = 768M|" /etc/php/${PHP_V}/cli/php.ini

# increase php apache memory limit
sed -i "s|^memory_limit.*|memory_limit = 64M|" /etc/php/${PHP_V}/apache2/php.ini

export HTTPS_PROXY_REQUEST_FULLURI=false # work around composer not working behind proxy
export COMPOSER_MEMORY_LIMIT=-1 # temporarily disable composer memory limits during install

# install drupal9
mkdir -p $WEBROOT
chown $USER:$USER $WEBROOT
turnkey-composer create-project drupal/recommended-project $WEBROOT --no-dev --no-interaction

# install drupal console
cd $WEBROOT
turnkey-composer require drupal/console --prefer-dist --optimize-autoloader --no-interaction --with-all-dependencies

# install drupal console launcher
cd / # drupal self-update fails from WEBROOT?!
wget -O /usr/local/bin/drupal -L https://drupalconsole.com/installer
chmod +x /usr/local/bin/drupal
drupal self-update

# install drush
cd $WEBROOT
turnkey-composer require drush/drush --no-interaction

# install global drush-launcher (drush installed as drupal module via composer above)
wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/latest/download/drush.phar
chmod +x /usr/local/bin/drush
drush self-update

CONF=$WEBROOT/web/sites/default/settings.php
cp $WEBROOT/web/sites/default/default.settings.php $CONF
LIBRARIES_PATH=$WEBROOT/libraries
mkdir -p $LIBRARIES_PATH/
chown -R $USER:$USER $WEBROOT

service mysql start
mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

cd $WEBROOT
turnkey-drush site-install standard -y \
    --account-name=$ADMIN_NAME \
    --account-pass=$ADMIN_PASS \
    --site-name="TurnKey\\\ Drupal9" \
    --db-url=mysql://$DB_USER:$DB_PASS@localhost/$DB_NAME

# download and install modules
MODULES="drupal/ctools \
         drupal/field_group \
         drupal/google_analytics \
         drupal/honeypot \
         drupal/imce \
         drupal/pathauto \
         drupal/token"
for module in $MODULES; do
    turnkey-composer require $module --no-interaction
done

turnkey-drush en -y \
    ctools \
    field_group \
    google_analytics \
    honeypot \
    pathauto

turnkey-drush cache-rebuild

# configure apache
a2dissite 000-default
a2ensite drupal9
a2enmod rewrite 
 
# insert "www.example.com" as default trusted_host (inithook will adjust)
NEW_LINES="\$settings['trusted_host_patterns'] = array\(\n\t'^www\\\.example\\\.com\$',\n\t'^(\\\d{1,3})\\\.(\\\d{1,3})\\\.(\\\d{1,3})\\\.(\\\d{1,3})$',\n\);\n"
sed -i "/trusted_host_patterns/,/\*\//{n;s|^$|${NEW_LINES}|}" $CONF

# disable poor mans cron and setup drush cron
cat >> $CONF << EOF

/**
 * Disable Poor Man's Cron:
 *
 * Drupal 9 enables the built-in Poor Man's Cron by default.
 * Poor Man's Cron relies on site activity to trigger Drupal's cron,
 * and is not well suited for low activity websites.
 *
 * We will use the Linux system cron and override Poor Man's Cron
 *
 * To re-enable Poor Man's Cron:
 *    Comment out the line below, and disable the system cron
 *    in /etc/cron.hourly/drupal9
 */
\$config['automated_cron.settings']['interval'] = 0;
EOF

CRON_DRUPAL=/etc/cron.hourly/drupal9
cat >$CRON_DRUPAL<<EOF
#!/bin/bash -e
# Trigger drush cron

[ -x /usr/local/bin/drush ] || exit 0

su www-data -s /bin/bash -c "/usr/local/bin/drush --quiet cron --root=/var/www/drupal9"
EOF
chmod +x $CRON_DRUPAL

# create welcome page
MYSQL_BATCH="mysql --batch --execute"

WELCOME='<p>Please follow these steps to set up and start using your website:</p><ol><li><strong>Configure your website:</strong> To get started, log in as <b>admin</b> and visit the <a href=\"/admin\">administration section</a>, where you can customize and configure all aspects of your website.</li><li><strong>Start posting content:</strong> When ready, delete this welcome and <a href=\"/node/add\">create content</a> for your website.</li></ol><p>For more information, please refer to the <a href=\"https://www.turnkeylinux.org/drupal9\">TurnKey Drupal9 release notes</a>, <a href=\"/admin/help\">help section</a>, or the <a href=\"http://drupal.org/handbooks\">online Drupal handbooks</a>. You may also post at the <a href=\"http://drupal.org/forum\">Drupal forum</a>, or view the wide range of <a href=\"http://drupal.org/support\">other support options</a> available.</p>'

$MYSQL_BATCH "INSERT INTO $DB_NAME.node (nid, vid, type, uuid, langcode) VALUES (1,1,'page','dbab9403-2ebd-4fb9-8a00-e764ce980ecd','en');"
$MYSQL_BATCH "INSERT INTO $DB_NAME.node__body (bundle, deleted, entity_id, revision_id, langcode, delta, body_value, body_summary, body_format) VALUES ('page',0,1,1,'en',0,'$WELCOME','$WELCOME','basic_html');"
$MYSQL_BATCH "INSERT INTO $DB_NAME.node_field_data (nid, vid, type, langcode, title, uid, status, created, changed, promote, sticky, revision_translation_affected, default_langcode) VALUES (1,1,'page','en','Welcome to TurnKey Drupal',1,1,1435831165,1435831165,1,0,1,1);"
$MYSQL_BATCH "INSERT INTO $DB_NAME.node_field_revision (nid, vid, langcode, title, uid, status, created, changed, promote, sticky, revision_translation_affected, default_langcode) VALUES (1,1,'en','Welcome to TurnKey Drupal',1,1,1435831165,1435831165,1,0,1,1);"
$MYSQL_BATCH "INSERT INTO $DB_NAME.node_revision (nid, vid, langcode, revision_timestamp, revision_uid, revision_log) VALUES (1,1,'en',1435831535,1,'');"
$MYSQL_BATCH "INSERT INTO $DB_NAME.node_revision__body (bundle, deleted, entity_id, revision_id, langcode, delta, body_value, body_summary, body_format) VALUES ('page',0,1,1,'en',0,'$WELCOME','$WELCOME','basic_html');"

service mysql stop

# unset proxy settings
unset HTTP_PROXY
