#!/bin/bash -e
# regenerate drupal10 hash_salt and mysql password

. /etc/default/inithooks

CONF=/var/www/drupal10/web/sites/default/settings.php

SALT=$(mcookie)
sed -i 's/^\($settings\['\''hash_salt'\''] =\).*/\1 '"'$SALT'"';/' $CONF

PASSWORD=$(mcookie)
sed -i "s|^\( *\)'password'.*|\1'password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=drupal10 --pass="$PASSWORD"

