#!/bin/bash -e
# set Drupal 10 admin password, email and domain

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/drupal10.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"
