#!/bin/bash
set -e

cd /var/www/drupal10
TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' INT TERM EXIT

set +e
/usr/local/bin/turnkey-composer audit --locked --no-interaction \
    --abandoned=report >"$TMPFILE" 2>&1
status=$?
set -e

case $status in
    0)
        ;;
    1)
        mail -s 'Drupal security updates available' root <"$TMPFILE"
        ;;
    *)
        cat "$TMPFILE" >&2
        exit "$status"
        ;;
esac
